name: minimo
description: "Un'applicazione minimalista per gestire gli alimenti e rudurre al minimo gli sprechi."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  unicons: ^1.0.0+2
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.9.1
  shared_preferences: ^2.5.3
  get_it: ^8.0.2
  provider: ^6.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/shopping_list_empty.png
    - assets/images/inventory_empty.png
    - assets/images/mascot_progress_circle_bad.png
    - assets/images/reduce_waste.jpg
    - assets/images/shopping_list.jpg
    - assets/images/manage_pantry.png
    - assets/images/start_your_journey.jpg
    - assets/images/badge_1.jpg
    - assets/images/badge_2.jpg
    - assets/images/badge_3.jpg
    - assets/images/badge_4.jpg
    - assets/images/badge_5.jpg
    - assets/images/badge_6.jpg
    - assets/images/app_icon.png
    - assets/images/splash_icon.png

  fonts:
    - family: ArticulatCF
      fonts:
        - asset: assets/fonts/ArticulatCF-Regular.otf
    - family: Recoleta
      fonts:
        - asset: assets/fonts/Recoleta-RegularDEMO.otf

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#48C5C6"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#48C5C6"
  image: assets/images/splash_icon.png
  android_gravity: center
  android_12:
    color: "#48C5C6"
    image: assets/images/splash_icon.png
    icon_background_color: "#48C5C6"